import Head from "next/head";
import {useSession} from "next-auth/react";
import HeaderBar from "@/components/home/HeaderBar";
import {UploadFilesComponent} from "@/components/upload/UploadComponent";

export default function Home() {
    const {data: session} = useSession();
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main
                className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                    <HeaderBar></HeaderBar>
            </main>
        </>
    );
}
